### ISSUE TITLE
Why no noarch?

### ISSUE THREAD

**Issue by maartenbreddels** [conda-forge/jupyter_server-feedstock#24]
Is there a reason or should we make this noarch ?

**Comment by bollwyvl** [comment]
#26 does (and now nothing else, as the `tests` thing is resolved).

A little more research reveals: if we rely on `jupyter_core` for the `pywin32` pin, we'd want to pin to `jupyter_core >=4.6.1` as that's when some of that functionality came over from `jupyter_client`: https://github.com/jupyter/jupyter_core/pull/163

I'd feel more comfortable if that pin was moved upstream, i guess...

**Comment by bollwyvl** [comment]
Ah, there's this: https://github.com/jupyter-server/jupyter_server/issues/281

It's just a bit of a lift to pull those changes over, and indeed raise the pin. I'll do the upstream PR and close #26.

**Comment by bollwyvl** [comment]
https://github.com/jupyter-server/jupyter_server/pull/357

**Comment by bollwyvl** [comment]
https://github.com/ipython/ipykernel/pull/564

**Comment by bollwyvl** [comment]
I think #58 will finally fix this. :tada:

**Comment by bollwyvl** [comment]
Closed by #58
