### ISSUE TITLE
Add support linux aarch64

### ISSUE THREAD

**Issue by holdenk** [conda-forge/jupyter_server-feedstock#43]
Currently this is cross-built for osx arm64, but for folks using jetsons or rpis having this installable for Linux aarch64 could be useful.

**Comment by bollwyvl** [comment]
If it works, #44 should fix this...

**Comment by bollwyvl** [comment]
@holdenk #44 was merged, will be up within the hour, presumably. please check the builds out, if you can (i have no such machines to test against), and re-open if you encounter issues.

**Comment by bollwyvl** [comment]
Build failed, kicked again... stay tuned...

https://github.com/conda-forge/jupyter_server-feedstock/runs/1798096495

**Comment by bollwyvl** [comment]
Ok, all :heavy_check_mark: 

```
linux-aarch64/jupyter_server-1.2.3-py36h2e20a7f_1.tar.bz2
linux-aarch64/jupyter_server-1.2.3-py36h704843e_1.tar.bz2
linux-aarch64/jupyter_server-1.2.3-py37hd9ded2f_1.tar.bz2
linux-aarch64/jupyter_server-1.2.3-py38h2063c64_1.tar.bz2
linux-aarch64/jupyter_server-1.2.3-py39ha65689a_1.tar.bz2
linux-ppc64le/jupyter_server-1.2.3-py36h270354c_1.tar.bz2
linux-ppc64le/jupyter_server-1.2.3-py36he7cccf2_1.tar.bz2
linux-ppc64le/jupyter_server-1.2.3-py37h35e4cab_1.tar.bz2
linux-ppc64le/jupyter_server-1.2.3-py38hf8b3453_1.tar.bz2
linux-ppc64le/jupyter_server-1.2.3-py39hc1b9086_1.tar.bz2
```

**Comment by holdenk** [comment]
Awesome, thanks so much for fixing this, let me try and install it on ARM after my morning coffee :)

**Comment by holdenk** [comment]
Sorry for my delay, just wanted to report back that this fixed the issue I was running into @bollwyvl and greatly sped up my container build times, so thank you :)
