### ISSUE TITLE
Use nbconvert-core?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jupyter_server-feedstock#86]
### Comment:

We could now start using `nbconvert-core`, which doesn't require `pandoc`.

This would make `jupyter_server` easier to install, for cases that wouldn't use `pandoc`, such as `voila`.

Other downstreams, such as `jupyterlab`, could choose to rely on full `nbconvert`.

### References
- upstream https://github.com/conda-forge/nbconvert-feedstock/issues/72

**Comment by minrk** [comment]
I think that's the right call
